laguage: cpp

env:
  global:
    - JABBA_HOME=$HOME/.jabba
    - TRAVIS_JDK=adopt@1.11.0-6
    - secure: "ChhfJ/6eUstimAmtp1/zTJd5hDzO6n4QuvXTjUSd+BdReHtUB9ICd41Pbs9i3M1GaDuCPG3z7iB+vk0ajpBLEDb/MI4Jg2KUV++Sir2ZQg0OrnK1Bm4ST6eODvfQlouYDfKWAzpD9HMp5EojSV+E+uLwrUa5a5cil0PHEMt7p6Nws3N+seml780C4YsgvniR8bpodFbcXMxYTEK+fn4C6klyMCshP92MDPkwFpIjGanUvN8W2TXt3X8cBsLtAfb5NrR5EBas9MDIpT4aeGAnrU+xmiaKz5PoRilBRyJtMVg939CAxekw580WEjc5Vy3Gc5qBTvUsCYCbEAB/cPKAaNThpm13SGUDgZmoW3rsls5YYs7wPb69GcpnEKOP9zxOH/AYNMoW141jBxhbS2R0h2uioQik5/fxFz68PB3vLvN4DjbCi2st+56x0p/qVEJLvaqQIKv8SfTFCKeOmSzBcECY0YEiuJxsyYhlj6WLWgw0+Uqc+d4pTI3u+rF1oy9X3320DOfOj1pRFLWxQ4SByv59nNixIdGYqbAhMGmX/SxQa5GiuDx9gQuktKsI78j93eIQ8/bUX8VRs61viO5SL4+fRgAyHWqZgTgyx12XAmpzYILgL46wXkAncQpDO6Y8GtDHz/9ixTlZj+azZiaaEi0W8eji50DaL6jgmRQLTX0="
    - secure: "crrKvLxrEvnI2k1k9mSFts40Wd2xkkT+oyjmxv0DNSq0n3ZSCMqD3vdiXKHP+fGbUmV+P3wYN7PYtCoXLxkWV/cOUkrzBHPYjLmdTQRIeRNunAhe7F7omuk6Nf3CsR/60zRawt4aUqHeyEojZ8zEvfqzPcVGNv/xtr0NfiOHaH/Ke8dPTwtJKeJ4rTVmXRhoJdai9I3W5VpO6aNLsMCXp0XChSkdgVY+qYKG6GhTxw12QXojv2ISmMRJLDinGzQyIfw+xB0mkGgpS0Rkp7VqDMWSkGwuItjxza/gw7nn/xROYwukxpKise8UUJ+ixBQg5I1ad82RMkF4UjRninY/Qib4QGfsuNgRfeIrarxM1zrER2kIcTy6LDhTsGkLCy44SXBAwfaPk1KEGfPZpxxFcgD+j+7zzl/0WETxxYFk1sxCWxdJ8Gt8Zt2RTH7CkCSQcGMsoMXaDQSYsvJQm8z9qHjmGd/h8/kJypB0RR/SGTfjK3tNk0ZagJo6JVxPR1h2Xnp8XAMVwH0PZGZWp3FF7xNGdSGsN764v6QIvXuo2qfw+4ynbBkxgZMuU2Inb+LR8TtGKplSvXZWSG1Gyu8opANZYmHM7rylht3MzUFQ33dsdYP3X54vS26QRr/HKNSulJqSOuB7WQVslNOpzEJ875687pB2jAVs4oq67fwR4Rc="
    - secure: "H93Exf+6TXiMVQ7BOaVf4b3cUrZwh9XNK+lQxR7VtucyucK/PTACe7rsJ0i2IgTEFH7Idt5EUWWfACsbyWVqWCr9iQxH2q2tAoWoV3teLrcp4F5Z9nVOTblQCEBZIvEntOcibBBvHG6Sv9dbf13iVT3Q69YfrACkum5r7jcWHBQkZV3AkR2rGu1AJMhT3hfD+uiadD8iErer4ZdNiqSljoHkFqamvGvO7QHIxJiTi/Q5gQ2tDumwJcMkJSH9/hgV6xoT3jvBNEagLi65iJuoiqDVczU9QkyfpAhvx3um50QarBb8CcAtLw41ls/xoN1wTnLHvohBejcm+jeMPfxSLvrKZ+ccw1ShJ0sy4ENIvjzK28WpO6BSE+8c6SIQ0IE8EZS4wJ1wu5dx0A5Cw9oecInwPu/6jQ0h+jhyXaeC/7fl3eLXCODhd21p1e1HkGCW2mCt/uhG/gXJIPg0im8aGQ66nUpiviYhoCHuRh144jhTbjLFF2etY2RjoqrVtwKA2tzSTA0iLd8pt+ndvnvKIxYpKCvmU8Fcdtry5I6rJhZpNh/MEHqyM8zh8jR32JnDXD12LbFrTYTPhPrU0J99ro5Km/jaaVPMYIwoxv3hIusLhAiLmlejDdhASqMwC00PVUGvrfpYzmy89ZOJmNbTKcL0lRNOS1SEta+ET5i6gnE="
    - secure: "RXTemiBbZBpSZkr4vRc7lcESnkX0XLu3YyKx7o2fPymvVrM3CRGvtAQdEOHbUqTHRs6PI1njZtSt0mQ4qsN1LhGWWbpw9GxgUrRN0X7Y/0+l2ji/CMnb4GBYTgLMJapM0R3jxzgCtEwn7wolG8rY2p47H37f1rHUNIsJk5Mr5roHzOWpMrLUx+SGDV6Ux1zN13LYPre4+PhvaveOF11/agcSKXTQf0lsr7ZKY4OO4Yyf6HfGq0gZw12DooAcX19haRCdAInoZDGHT1QIZgg1XQ2slbKF5lLp9wNOAnI48NuhJzPAh3Zuil94SdKr19iSOVhRxOQa2zishNLrheDogku6EUmIgSc0MluPvroW0zP8DMa2sRQtyFS8CuqFr7+ynTz0GxwIcjL6NpFEVwyXKHl3U2pkyirUqIjbRWmfUxUlr0JQ8scV5eg79X8h1mfKvOw8Ifi6pZd5sA57OV4/BOD2uUAxSRA3o86wAHbe1wMpEnK5mvf5GDtVcQxhk97m6sf++QD/dF6vEVZQ9iCMS0wKlXvJD9/GunK1bV5R3TiIe+MWuexWv/h/LqM2qQu6dO4/hB4YZYanfxisPN8Jfmo47kDLAA/Z86uwzfycZwrvkUAyKfWK1WOVWK7w7wBi+cCNl78dU6IFezJjgy0btf/rWpEdFf6z/duXVdBqIF8="
    - secure: "TiBELD8QquuYo4sP1ukHWHtsV8MHNXC4SxPIOVhiavPJa6x6ecPmGYVTtVuMiEbMzpfLVh26t5ZDU0xNf/0+vL99PXtdF7JvpV2hRY78ivE8escTDF27F1wFcc2T46SwOkZFCDUkBIqcPZyIpUpmmBwQFzzB00zzhw/howdFRLRfqhk8w1TQZ7M96OcDEGGufN05RUp3Y4EHmsUxP5/JqkkUa+foDTxObUDl1GzJNhNd2rtRT6VE/eQ4DPic2ZehAhBwFMSwAWt0x5mTY8Jkc9Pzso8H0bYtVqv0tOWLnydiVSnIflnrJocwlOxnQPKa3g+R/U68kFCDkxD7JFJtNBEN232elePuKCUeyfdbjLMq/IDDozCKIIYWJt5v6XdF6uTo2iIMxRuJXoxnw65HXWRvq+xsgJxpXPhrQcszArWg1c8k43fAiqoYKibqRfOF7/VCDLHeblzVZ7HO4QJTXWjKV3ocTMCKpnBgJWILSr+LQXhx8/yvdWvtAJwSs9mWZ4qd0Up7Qzp/tmasmCR2JdBC/cO7sdGYTDKoC5HvVzYZZZR5+idxTPbak0XGv6u9/f/QQYbtpUV/kgiprOEOrqs8mc65e5gik9cVlNA6rskBQDpUl92SZkjaBQI9nAvjmxmrUW99NHOwh2PO9r1CS+QopN5h/KSk/DNPqsa6n7I="

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.jabba"

before_cache:
- rm -rf "$HOME/.m2/repository/com/github/java-native"
- rm -rf "$HOME/.m2/repository/io/github/java-native"

matrix:
  include:
  - os: linux
    sudo: false
    env:
      - MAVEN_MODULE=linux-x86_64-64
      - MAVEN_PROFILE=linux-x86_64-64
    addons:
      apt:
        packages:
          - cmake
          - g++-5
  - os: linux
    sudo: false
    env:
      - MAVEN_MODULE=linux-x86_32-32
      - MAVEN_PROFILE=linux-x86_32-32
    addons:
      apt:
        packages:
          - cmake
          - g++-5-multilib
          - linux-libc-dev:i386
  - os: linux
    sudo: false
    arch: arm64
    env:
      - MAVEN_MODULE=linux-aarch_64-64
      - MAVEN_PROFILE=linux-aarch_64-64
    addons:
      apt:
        packages:
          - cmake
          - g++-5
  - os: linux
    sudo: false
    arch: amd64
    env:
      - MAVEN_MODULE=linux-arm_32-32
      - MAVEN_PROFILE=linux-arm_32-32
    addons:
      apt:
        packages:
          - cmake
          # we want g++-5 explicitly here.
          - g++-5-arm-linux-gnueabi
  - os: linux
    sudo: false
    arch: amd64
    env:
      - MAVEN_MODULE=linux-arm_32-32-hf
      - MAVEN_PROFILE=linux-arm_32-32-hf
    addons:
      apt:
        packages:
          - cmake
          # we want g++-5 explicitly here.
          - g++-5-arm-linux-gnueabihf
  - os: linux
    sudo: false
    arch: ppc64le
    env:
      - MAVEN_MODULE=linux-ppcle_64-64
      - MAVEN_PROFILE=linux-ppcle_64-64
    addons:
      apt:
        packages:
          - cmake
          - g++-5
  - os: osx
    language: java
    env:
      - MAVEN_MODULE=osx_x86_64-64
      - MAVEN_PROFILE=osx_x86_64-64
    osx_image: xcode10.1
    addons:
      homebrew:
        packages:
          - gnupg

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_CPU_ARCH" != "ppc64le" ]; then curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash && . $JABBA_HOME/jabba.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash && . $JABBA_HOME/jabba.sh; fi
  - gpg --version

install:
  # jabba has no ppc64 support atm, lets use the default jdk.
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_CPU_ARCH" != "ppc64le" ]; then $JABBA_HOME/bin/jabba install $TRAVIS_JDK; jabba use $TRAVIS_JDK; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then $JABBA_HOME/bin/jabba install $TRAVIS_JDK; jabba use $TRAVIS_JDK; fi
  # manual jdk installation for the moment.
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_CPU_ARCH" == "ppc64le" ]; then
      export JAVA_HOME="$HOME/.jabba/jdk/adopt@1.11.0-6"
      mkdir -p "$JAVA_HOME"
      curl -sL "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.6_10.tar.gz" -o - \
      | tar -C "$HOME/.jabba/jdk/adopt@1.11.0-6" --strip-components=1 -xzvf -
      export PATH="$JAVA_HOME/bin:$PATH"
    fi
  - java -version

script:
- ./mvnw --batch-mode -Pdocs,deploy,$MAVEN_PROFILE -Dgpg.skip=true verify -pl $MAVEN_MODULE -am

after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" == "" ]; then
    openssl aes-256-cbc -K $encrypted_19397dde2ef8_key -iv $encrypted_19397dde2ef8_iv -in .deployment/signingkey.asc.enc -out .deployment/signingkey.asc -d
    gpg --batch --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --import .deployment/signingkey.asc
    gpg --batch --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring --import .deployment/signingkey.asc
    ./mvnw --batch-mode -Pdocs,deploy,$MAVEN_PROFILE --settings .deployment/m2-settings.xml -Dheader.deploy.skip=true -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg -Dgpg.keyname=0x196A72C1 -Dgpg.passphrase="$GPG_PASSPHRASE" deploy -pl $MAVEN_MODULE -am
  fi

notifications:
  slack:
    on_failure: change
    rooms:
      - java-native:${java-native}#jssc-native

